USE planner;
 
CREATE TABLE history_list
(
    action_id INT PRIMARY KEY IDENTITY NOT NULL,
	program_id INT NOT NULL,
	action_description NVARCHAR(MAX),
	action_comment NVARCHAR(MAX),
    worker_id INT NOT NULL,
    worker NVARCHAR(100) NOT NULL,
	date_of_change DATE NOT NULL,
	old_meta BIT,
	new_meta BIT,
	old_work_date DATE,
	new_work_date DATE,
	old_cenz_rate NVARCHAR(MAX),
	new_cenz_rate NVARCHAR(MAX),
	old_cenz_worker_id INT,
	new_cenz_worker_id INT,
	old_tags NVARCHAR(MAX),
	new_tags NVARCHAR(MAX),
	old_inoagent NVARCHAR(MAX),
	new_inoagent NVARCHAR(MAX),
	old_lgbt NVARCHAR(MAX),
	new_lgbt NVARCHAR(MAX),
	old_sig NVARCHAR(MAX),
	new_sig NVARCHAR(MAX),
	old_obnazh NVARCHAR(MAX),
	new_obnazh NVARCHAR(MAX),
	old_narc NVARCHAR(MAX),
	new_narc NVARCHAR(MAX),
	old_mat NVARCHAR(MAX),
	new_mat NVARCHAR(MAX),
	old_other NVARCHAR(MAX),
	new_other NVARCHAR(MAX),
	old_editor NVARCHAR(MAX),
	new_editor NVARCHAR(MAX)
);