SELECT TOP (1000) [action_id]
      ,[program_id]
      ,[action_description]
      ,[action_comment]
      ,[worker_id]
      ,[worker]
      ,[change_date]
      ,[old_meta]
      ,[new_meta]
      ,[old_work_date]
      ,[new_work_date]
      ,[old_cenz_rate]
      ,[new_cenz_rate]
      ,[old_cenz_worker]
      ,[new_cenz_worker]
      ,[old_tags]
      ,[new_tags]
      ,[old_inoagent]
      ,[new_inoagent]
      ,[old_lgbt]
      ,[new_lgbt]
      ,[old_sig]
      ,[new_sig]
      ,[old_obnazh]
      ,[new_obnazh]
      ,[old_narc]
      ,[new_narc]
      ,[old_mat]
      ,[new_mat]
      ,[old_other]
      ,[new_other]
      ,[old_editor]
      ,[new_editor]
  FROM [planner].[dbo].[history_list]
  WHERE [program_id] = 7129
