"""
Django settings for planner project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
SERVICE_TYPE = os.getenv('SERVICE_TYPE', 'internal')
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

MEDIA_SERVER_IP = os.getenv('MEDIA_SERVER_IP')
MEDIA_SERVER_PORT = os.getenv('MEDIA_SERVER_PORT')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
ALLOWED_HOSTS.extend(['tvfab.local', 'localhost', '192.168.33.3'])
# if DEBUG:
#     ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '0.0.0.0'])

# Для работы HTTPS
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
CSRF_TRUSTED_ORIGINS.extend([
    'http://192.168.33.3',
    'http://localhost',
    'http://www.tvfab.local',
    'https://192.168.33.3',
    'https://localhost',
    'https://www.tvfab.local',
])

# Безопасные куки
SESSION_COOKIE_SECURE = True      # Только по HTTPS
SESSION_COOKIE_HTTPONLY = True    # Недоступны из JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Дополнительные заголовки безопасности
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Настройки для стриминга
STREAMING_HLS_URL = f'https://{MEDIA_SERVER_IP}:{MEDIA_SERVER_PORT}/hls/'

# Доверять заголовкам от Nginx
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Celery Configuration
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
CELERY_BROKER_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_ENABLE_UTC = True

# Опционально: настройки расписания для периодических задач
CELERY_BEAT_SCHEDULE = {
    # 'update-no-material': {
    #     'task': 'tools.tasks.cleanup_old_tasks',
    #     'schedule': crontab(hour=3, minute=0),  # Каждый день в 3:00
    # },
}

# Application definition
INSTALLED_APPS = [
    "daphne",
    "channels",
    "home",
    "main",
    "workers",
    "desktop",
    "otk",
    "on_air_report",
    "advanced_search",
    "common_pool",
    "messenger_static",
    "admin_work_panel",
    "distribution",
    "playlist",
    "tools",
    "notifications",
    "schedule_perspective",
    "file_manager",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages"
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [{
                "address": f"redis://:{REDIS_PASSWORD}@{MEDIA_SERVER_IP}:{REDIS_PORT}/1",
            }],
        },
    },
}

# WSGI application
WSGI_APPLICATION = 'planner.wsgi.application'

# ASGI application
ASGI_APPLICATION = 'planner.asgi.application'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "workers.middleware.WorkTimeTrackingMiddleware",
]

# Настройки для S3 (MinIO)
AWS_ACCESS_KEY_ID = os.getenv('MINIO_DJANGO_USER')
AWS_SECRET_ACCESS_KEY = os.getenv('MINIO_DJANGO_PASSWORD')

S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 'http://minio:9000')
AWS_S3_USE_SSL = os.getenv('AWS_S3_USE_SSL', True)  # HTTPS
AWS_S3_VERIFY = os.getenv('AWS_S3_VERIFY')

# Чтобы файлы не были общедоступными (загружаются через приложение)
AWS_DEFAULT_ACL = os.getenv('AWS_DEFAULT_ACL', 'private')
AWS_QUERYSTRING_AUTH = True  # генерирует временные подписанные URL

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

ROOT_URLCONF = "planner.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                'django.template.context_processors.media',
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

OPLAN_DB = 'oplan3'
OPLAN_USER = os.getenv('DB_MSSQL_USER')
OPLAN_PASSWORD = os.getenv('DB_MSSQL_PASSWORD')
OPLAN_HOST = os.getenv('DB_MSSQL_HOST')
OPLAN_PORT = os.getenv('DB_MSSQL_PORT')

PLANNER_DB = 'planner'
PLANNER_USER = os.getenv('DB_MSSQL_USER')
PLANNER_PASSWORD = os.getenv('DB_MSSQL_PASSWORD')
PLANNER_HOST = os.getenv('DB_MSSQL_HOST')
PLANNER_PORT = os.getenv('DB_MSSQL_PORT')

ODBC_DRIVER = os.getenv('ODBC_DRIVER', 'ODBC Driver 17 for SQL Server')

MONGO_DB = 'planner'
DB_MONGO_HOST = os.getenv('DB_MONGO_HOST')
DB_MONGO_PORT = os.getenv('DB_MONGO_PORT')
MONGO_USER = os.getenv('DB_MONGO_USER')
MONGO_PASSWORD = os.getenv('DB_MONGO_PASSWORD')
MONGO_HOST =  f'mongodb://{MONGO_USER}:{MONGO_PASSWORD}@{DB_MONGO_HOST}:{DB_MONGO_PORT}'

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": PLANNER_DB,
        "USER": PLANNER_USER,
        "PASSWORD": PLANNER_PASSWORD,
        "HOST": PLANNER_HOST,
        # "PORT": "1433",
        "OPTIONS": {
            "driver": ODBC_DRIVER,
            "extra_params": "Encrypt=yes;TrustServerCertificate=yes"
        },
    },
    OPLAN_DB: {
        "ENGINE": "mssql",
        "NAME": OPLAN_DB,
        "USER": OPLAN_USER,
        "PASSWORD": OPLAN_PASSWORD,
        "HOST": OPLAN_HOST,
        # "PORT": "1433",
        "OPTIONS": {
            "driver": ODBC_DRIVER,
            "extra_params": "Encrypt=yes;TrustServerCertificate=yes"
        },
    },
    PLANNER_DB: {
        "ENGINE": "mssql",
        "NAME": PLANNER_DB,
        "USER": PLANNER_USER,
        "PASSWORD": PLANNER_PASSWORD,
        "HOST": PLANNER_HOST,
        # "PORT": "1433",
        "OPTIONS": {
            "driver": ODBC_DRIVER,
            "extra_params": "Encrypt=yes;TrustServerCertificate=yes"
        },
    },
    "ffmpeg": {
        "ENGINE": "django_mongodb_engine",
        "NAME": MONGO_DB,
        'HOST': MONGO_HOST,
        "OPTIONS": {
            "authSource": "admin",
        },
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
DEFAULT_LOG_DIR = os.path.join(BASE_DIR, 'logs/')

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_POSTERS = os.path.join(BASE_DIR, 'media/posters')
MEDIA_WAVEFORMS = os.path.join(BASE_DIR, 'media/waveforms')
SFTP_FOLDER = os.getenv('SFTP_FOLDER', '/mnt/sftp/Planner')

CURRENT_CENZ_DIR = r'\\192.168.80.5\ContentA\0_INTERNET_VIDEO\_CENZ'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'planner-cash',  # Уникальное имя для локального кэша
    }
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = '/authorize/login_worker/'

# DATE_INPUT_FORMATS = ["%d.%m.%Y", "%d-%m-%Y"]
# USE_L10N = False