version: '3.8'

services:
  dev:
    container_name: media_task_dev
    build:
      context: ..  # Собираем из корня проекта
      dockerfile: docker/Dockerfile.web  # Путь к Dockerfile относительно контекста
    command: python planner/manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    working_dir: /app
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - planner-network

  prod:
    container_name: media_task_prod
    build:
      context: ..  # Собираем из корня проекта
      dockerfile: docker/Dockerfile.web  # Путь к Dockerfile относительно контекста
    command: >
      sh -c "
      cd /app/planner &&
      gunicorn planner.wsgi:application 
      --bind 0.0.0.0:8000 
      --workers 10 
      --timeout 240 
      --access-logfile - 
      --error-logfile -
      "
    environment:
      - DJANGO_SETTINGS_MODULE=planner.settings
      - PYTHONPATH=/app
      - BIND=0.0.0.0:8000
    volumes:
      - ..:/app
    working_dir: /app
    expose:
      - "8000"
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - planner-network

  nginx:
    container_name: media_task_nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
      - ../planner/static:/app/planner/static:ro
      - ../planner/media:/app/planner/media:ro
    ports:
      - "8000:8000"
    depends_on:
      - prod
    networks:
      - planner-network

  celery_worker:
    container_name: media_task_celery_worker
    build:
      context: ..  # Собираем из корня проекта
      dockerfile: docker/Dockerfile.worker
    command: >
      sh -c "
      cd /app/planner &&
      celery -A planner worker --loglevel=info --concurrency=4
      "
    volumes:
      - ..:/app
      - /mnt:/mnt
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=planner.settings
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - planner-network

  # Flower для мониторинга Celery с Basic Auth
  flower:
    container_name: media_task_flower
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    command: >
      sh -c "
      cd /app/planner &&
      celery -A planner --broker=redis://redis:6379/0 flower 
      --basic_auth=$${FLOWER_USER}:$${FLOWER_PASSWORD} 
      --address=0.0.0.0
      --port=5555 
      "
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=planner.settings
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_USER=admin
      - FLOWER_PASSWORD=media123
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      - redis
      - celery_worker
    networks:
      - planner-network

  redis:
    container_name: media_task_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - planner-network

networks:
  planner-network:
    name: planner-network
    external: true
    driver: bridge