# Generated by Django 5.0.13 on 2025-05-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvancedSearch",
            fields=[
                (
                    "owner",
                    models.IntegerField(
                        default=1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="owner",
                    ),
                ),
                ("search_id", models.IntegerField()),
            ],
        ),
    ]
