# Generated by Django 5.0.13 on 2025-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonPool",
            fields=[
                (
                    "owner",
                    models.IntegerField(
                        default=1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="owner",
                    ),
                ),
                ("sql_set", models.IntegerField(default=100)),
            ],
        ),
    ]
